"""Remove unique from league.title

Revision ID: 1d8c0f1b954f
Revises: dfbd11802e7a
Create Date: 2020-04-19 01:39:21.786264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8c0f1b954f'
down_revision = 'dfbd11802e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.create_foreign_key('tournament_id', 'tournaments', ['tournament_id'], ['id'])

    # ### end Alembic commands ###
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
