"""games update

Revision ID: 86ee157bb504
Revises: 1bdb23628375
Create Date: 2020-04-20 10:56:47.255850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ee157bb504'
down_revision = '1bdb23628375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('judge_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('judge_id', 'users', ['judge_id'], ['id'])
        batch_op.drop_column('finish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint('judge_id', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('judge_id')

    # ### end Alembic commands ###
